language: python

env:
  - C_VERSION=12
  - C_VERSION=20

python:
  - "2.7"
  - "3.4"

#services: # removed to try to get before_install to use custom versions
#  - cassandra

before_install:
  - sudo echo "deb http://www.apache.org/dist/cassandra/debian ${C_VERSION}x main" | sudo tee -a /etc/apt/sources.list
  - sudo echo "deb-src http://www.apache.org/dist/cassandra/debian ${C_VERSION}x main" | sudo tee -a /etc/apt/sources.list
  - sudo gpg --keyserver pgp.mit.edu --recv-keys F758CE318D77295D
  - sudo gpg --export --armor F758CE318D77295D | sudo apt-key add -
  - sudo gpg --keyserver pgp.mit.edu --recv-keys 2B5C1B00
  - sudo gpg --export --armor 2B5C1B00 | sudo apt-key add -
  - sudo apt-get update
#  - sudo rm /etc/security/limits.d/cassandra.conf # travis apparently already has this file
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y cassandra
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
  - sudo service cassandra start

install:
  - "pip install -r requirements.txt --use-mirrors"
    #- "pip install pytest --use-mirrors"

script:
#  - while [ ! -f /var/run/cassandra.pid ] ; do sleep 1 ; done # wait until cassandra is ready, i don't think this is necessary anymore, and it seems to hang
  - "nosetests --no-skip"
    #  - "py.test cqlengine/tests/"
