language: python
python: 2.7
env:
  - TOX_ENV=py26 CASS_VER=21 CASS_DRIVER_NO_CYTHON=1
  - TOX_ENV=py26 CASS_VER=21
  - TOX_ENV=py27 CASS_VER=12 CASS_DRIVER_NO_CYTHON=1
  - TOX_ENV=py27 CASS_VER=20 CASS_DRIVER_NO_CYTHON=1
  - TOX_ENV=py27 CASS_VER=21 CASS_DRIVER_NO_CYTHON=1
  - TOX_ENV=py27 CASS_VER=21
  - TOX_ENV=py33 CASS_VER=21 CASS_DRIVER_NO_CYTHON=1
  - TOX_ENV=py33 CASS_VER=21
  - TOX_ENV=py34 CASS_VER=21 CASS_DRIVER_NO_CYTHON=1
  - TOX_ENV=py34 CASS_VER=21
  - TOX_ENV=pypy CASS_VER=21 CASS_DRIVER_NO_CYTHON=1
  - TOX_ENV=pypy3 CASS_VER=21 CASS_DRIVER_NO_CYTHON=1

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y build-essential python-dev
  - sudo apt-get install -y pypy-dev
  - sudo apt-get install -y libev4 libev-dev

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
